///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HBAuto_Install2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ConfirmHBInstallUpdate recording.
    /// </summary>
    [TestModule("5c4bcb30-1bc7-4d62-9bdd-a7908e787aa7", ModuleType.Recording, 1)]
    public partial class ConfirmHBInstallUpdate : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HBAuto_Install2Repository repository.
        /// </summary>
        public static HBAuto_Install2Repository repo = HBAuto_Install2Repository.Instance;

        static ConfirmHBInstallUpdate instance = new ConfirmHBInstallUpdate();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ConfirmHBInstallUpdate()
        {
            YearVersion = "2018.1";
            HBInstallLocation = "C:\\HeavyBid\\";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ConfirmHBInstallUpdate Instance
        {
            get { return instance; }
        }

#region Variables

        string _YearVersion;

        /// <summary>
        /// Gets or sets the value of variable YearVersion.
        /// </summary>
        [TestVariable("32b62d6c-e049-47ea-a435-28ef1262d215")]
        public string YearVersion
        {
            get { return _YearVersion; }
            set { _YearVersion = value; }
        }

        string _HBInstallLocation;

        /// <summary>
        /// Gets or sets the value of variable HBInstallLocation.
        /// </summary>
        [TestVariable("8c664762-c44e-4fba-97d1-e6344f6ad9d1")]
        public string HBInstallLocation
        {
            get { return _HBInstallLocation; }
            set { _HBInstallLocation = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            // B.3
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nB.3\r\nValidating AttributeRegex (Text~'HeavyBid') on item 'HeavyBidServerSetup.Titlebar'.", repo.HeavyBidServerSetup.TitlebarInfo, new RecordItemIndex(0));
                Validate.AttributeRegex(repo.HeavyBidServerSetup.TitlebarInfo, "Text", new Regex("HeavyBid"), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            // B.3
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nB.3\r\nValidating AttributeRegex (Text~'Setup') on item 'HeavyBidServerSetup.Titlebar'.", repo.HeavyBidServerSetup.TitlebarInfo, new RecordItemIndex(1));
                Validate.AttributeRegex(repo.HeavyBidServerSetup.TitlebarInfo, "Text", new Regex("Setup"), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
            // B.3
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nB.3\r\nValidating AttributeRegex (Text~$YearVersion) on item 'HeavyBidServerSetup.Titlebar'.", repo.HeavyBidServerSetup.TitlebarInfo, new RecordItemIndex(2));
                Validate.AttributeRegex(repo.HeavyBidServerSetup.TitlebarInfo, "Text", new Regex(YearVersion), null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
            // Check if testing for pulling file path from previous HB install
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nCheck if testing for pulling file path from previous HB install\r\nValidating AttributeContains (Text>$HBInstallLocation) on item 'HeavyBidServerSetup.ConfirmFilepathTextbox'.", repo.HeavyBidServerSetup.ConfirmFilepathTextboxInfo, new RecordItemIndex(3));
                //Validate.AttributeContains(repo.HeavyBidServerSetup.ConfirmFilepathTextboxInfo, "Text", HBInstallLocation, null, false);
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(3)); }
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'HeavyBidServerSetup.UpdateButton'", repo.HeavyBidServerSetup.UpdateButtonInfo, new ActionTimeout(60000), new RecordItemIndex(4));
            repo.HeavyBidServerSetup.UpdateButtonInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidServerSetup.UpdateButton' at Center.", repo.HeavyBidServerSetup.UpdateButtonInfo, new RecordItemIndex(5));
            repo.HeavyBidServerSetup.UpdateButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ConvertMultipleEstimates.CancelButton' at Center.", repo.ConvertMultipleEstimates.CancelButtonInfo, new RecordItemIndex(6));
            repo.ConvertMultipleEstimates.CancelButton.Click();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 15m to exist. Associated repository item: 'HeavyBidServerSetup.FinishButton'", repo.HeavyBidServerSetup.FinishButtonInfo, new ActionTimeout(900000), new RecordItemIndex(7));
            repo.HeavyBidServerSetup.FinishButtonInfo.WaitForExists(900000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HeavyBidServerSetup.FinishButton' at Center.", repo.HeavyBidServerSetup.FinishButtonInfo, new RecordItemIndex(8));
            repo.HeavyBidServerSetup.FinishButton.Click();
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
