///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HBAuto_Install2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteHBFolder recording.
    /// </summary>
    [TestModule("36e73264-f71b-4f3f-a776-7c21ce9c649a", ModuleType.Recording, 1)]
    public partial class DeleteHBFolder : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HBAuto_Install2Repository repository.
        /// </summary>
        public static HBAuto_Install2Repository repo = HBAuto_Install2Repository.Instance;

        static DeleteHBFolder instance = new DeleteHBFolder();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteHBFolder()
        {
            InstallLocation = "C:\\HeavyBid";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteHBFolder Instance
        {
            get { return instance; }
        }

#region Variables

        string _InstallLocation;

        /// <summary>
        /// Gets or sets the value of variable InstallLocation.
        /// </summary>
        [TestVariable("6a8a0737-fbc0-4113-a706-ee4756edbac3")]
        public string InstallLocation
        {
            get { return _InstallLocation; }
            set { _InstallLocation = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            DeleteHBDirectory(InstallLocation);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
