///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HBAuto_Install2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HBAuto_Install2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("3ee3ded7-920f-4216-8ac3-03a745940125")]
    public partial class HBAuto_Install2Repository : RepoGenBaseFolder
    {
        static HBAuto_Install2Repository instance = new HBAuto_Install2Repository();
        HBAuto_Install2RepositoryFolders.HeavyBidServerSetupAppFolder _heavybidserversetup;
        HBAuto_Install2RepositoryFolders.ConvertMultipleEstimatesAppFolder _convertmultipleestimates;
        HBAuto_Install2RepositoryFolders.HeavyBidPopupAppFolder _heavybidpopup;
        HBAuto_Install2RepositoryFolders.ExcelRelatedFolder _excelrelated;
        HBAuto_Install2RepositoryFolders.ProgramsAndFeaturesAppFolder _programsandfeatures;
        HBAuto_Install2RepositoryFolders.HeavyBidUninstallAppFolder _heavybiduninstall;

        /// <summary>
        /// Gets the singleton class instance representing the HBAuto_Install2Repository element repository.
        /// </summary>
        [RepositoryFolder("3ee3ded7-920f-4216-8ac3-03a745940125")]
        public static HBAuto_Install2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HBAuto_Install2Repository() 
            : base("HBAuto_Install2Repository", "/", null, 0, false, "3ee3ded7-920f-4216-8ac3-03a745940125", ".\\RepositoryImages\\HBAuto_Install2Repository3ee3ded7.rximgres")
        {
            _heavybidserversetup = new HBAuto_Install2RepositoryFolders.HeavyBidServerSetupAppFolder(this);
            _convertmultipleestimates = new HBAuto_Install2RepositoryFolders.ConvertMultipleEstimatesAppFolder(this);
            _heavybidpopup = new HBAuto_Install2RepositoryFolders.HeavyBidPopupAppFolder(this);
            _excelrelated = new HBAuto_Install2RepositoryFolders.ExcelRelatedFolder(this);
            _programsandfeatures = new HBAuto_Install2RepositoryFolders.ProgramsAndFeaturesAppFolder(this);
            _heavybiduninstall = new HBAuto_Install2RepositoryFolders.HeavyBidUninstallAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3ee3ded7-920f-4216-8ac3-03a745940125")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HeavyBidServerSetup folder.
        /// </summary>
        [RepositoryFolder("9c66c658-82ce-4ae5-90ec-bf2630d207b0")]
        public virtual HBAuto_Install2RepositoryFolders.HeavyBidServerSetupAppFolder HeavyBidServerSetup
        {
            get { return _heavybidserversetup; }
        }

        /// <summary>
        /// The ConvertMultipleEstimates folder.
        /// </summary>
        [RepositoryFolder("91d0eedc-616b-4906-ab8f-663e09e1d2b0")]
        public virtual HBAuto_Install2RepositoryFolders.ConvertMultipleEstimatesAppFolder ConvertMultipleEstimates
        {
            get { return _convertmultipleestimates; }
        }

        /// <summary>
        /// The HeavyBidPopup folder.
        /// </summary>
        [RepositoryFolder("7b35272b-0f7e-4744-9841-fb5b2c0b875d")]
        public virtual HBAuto_Install2RepositoryFolders.HeavyBidPopupAppFolder HeavyBidPopup
        {
            get { return _heavybidpopup; }
        }

        /// <summary>
        /// The ExcelRelated folder.
        /// </summary>
        [RepositoryFolder("588390a4-0599-4f61-8881-14ed2ef9d0fb")]
        public virtual HBAuto_Install2RepositoryFolders.ExcelRelatedFolder ExcelRelated
        {
            get { return _excelrelated; }
        }

        /// <summary>
        /// The ProgramsAndFeatures folder.
        /// </summary>
        [RepositoryFolder("900ba1a3-8153-4751-8e0d-8cca1362b5c3")]
        public virtual HBAuto_Install2RepositoryFolders.ProgramsAndFeaturesAppFolder ProgramsAndFeatures
        {
            get { return _programsandfeatures; }
        }

        /// <summary>
        /// The HeavyBidUninstall folder.
        /// </summary>
        [RepositoryFolder("82b00af4-ca5f-4ecf-a138-80c06109b889")]
        public virtual HBAuto_Install2RepositoryFolders.HeavyBidUninstallAppFolder HeavyBidUninstall
        {
            get { return _heavybiduninstall; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class HBAuto_Install2RepositoryFolders
    {
        /// <summary>
        /// The HeavyBidServerSetupAppFolder folder.
        /// </summary>
        [RepositoryFolder("9c66c658-82ce-4ae5-90ec-bf2630d207b0")]
        public partial class HeavyBidServerSetupAppFolder : RepoGenBaseFolder
        {
            HBAuto_Install2RepositoryFolders.ButtonsFolder _buttons;
            HBAuto_Install2RepositoryFolders.TextContainersForValidationFolder _textcontainersforvalidation;
            RepoItemInfo _titlebarInfo;
            RepoItemInfo _titletextInfo;
            RepoItemInfo _maintextInfo;
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _iacceptthetermsinthelicenseagreemInfo;
            RepoItemInfo _standaloneinstalltypeInfo;
            RepoItemInfo _multiuserinstalltypeInfo;
            RepoItemInfo _traininginstalltypeInfo;
            RepoItemInfo _updatetoInfo;
            RepoItemInfo _confirmfilepathtextboxInfo;
            RepoItemInfo _updatebuttonInfo;
            RepoItemInfo _finishbuttonInfo;
            RepoItemInfo _filepathtextboxInfo;

            /// <summary>
            /// Creates a new HeavyBidServerSetup  folder.
            /// </summary>
            public HeavyBidServerSetupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidServerSetup", "/form[@title~'HeavyBid' and @title~'Setup']", parentFolder, 30000, null, false, "9c66c658-82ce-4ae5-90ec-bf2630d207b0", "")
            {
                _buttons = new HBAuto_Install2RepositoryFolders.ButtonsFolder(this);
                _textcontainersforvalidation = new HBAuto_Install2RepositoryFolders.TextContainersForValidationFolder(this);
                _titlebarInfo = new RepoItemInfo(this, "Titlebar", "titlebar", 30000, null, "35bf72d1-45be-4453-9819-3d2d323b1b63");
                _titletextInfo = new RepoItemInfo(this, "TitleText", "text[@accessiblerole~'StaticText'][2]", 30000, null, "7981f32a-02cb-4ba9-9c4a-0177f8be1a32");
                _maintextInfo = new RepoItemInfo(this, "MainText", "text[@accessiblerole~'StaticText'][1]", 30000, null, "b84dd048-102c-4a61-8186-92104482d0e5");
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "button[@text~'Next']", 30000, null, "a2075e6e-eeac-4628-9811-a556dc9c6496");
                _iacceptthetermsinthelicenseagreemInfo = new RepoItemInfo(this, "IAcceptTheTermsInTheLicenseAgreem", "checkbox[@text~'terms']", 30000, null, "0eb1a8d3-4498-449a-abb3-dce214c16a4e");
                _standaloneinstalltypeInfo = new RepoItemInfo(this, "StandaloneInstallType", "?/?/radiobutton[@text~'Standalone']", 30000, null, "449b2c02-4d5e-4d8a-90d2-b225684194de");
                _multiuserinstalltypeInfo = new RepoItemInfo(this, "MultiUserInstallType", "?/?/radiobutton[@text~'Multi-user']", 30000, null, "00c47a49-1db2-4aad-9b8a-3eab2bf98638");
                _traininginstalltypeInfo = new RepoItemInfo(this, "TrainingInstallType", "?/?/radiobutton[@text~'Training']", 30000, null, "dbad87df-3fd8-4bc1-9541-b7c60e72fa06");
                _updatetoInfo = new RepoItemInfo(this, "UpdateTo", "?/?/radiobutton[@text~'Update']", 30000, null, "e6a51ee8-67a2-4082-be9b-b514ec14d9fd");
                _confirmfilepathtextboxInfo = new RepoItemInfo(this, "ConfirmFilepathTextbox", "text[@text~'install HeavyBid in:']", 30000, null, "ec43ca31-f9f3-442d-8db1-fb90bd3baee3");
                _updatebuttonInfo = new RepoItemInfo(this, "UpdateButton", "button[@text~'Update']", 30000, null, "9c99b1a2-54ec-4e70-8da6-e901a590d643");
                _finishbuttonInfo = new RepoItemInfo(this, "FinishButton", "button[@text~'Finish']", 30000, null, "a7259cce-3e74-4465-8f9d-93f01197f353");
                _filepathtextboxInfo = new RepoItemInfo(this, "FilepathTextbox", "text[@accessiblerole='Text']", 30000, null, "bde8679d-1119-4c02-a1b5-1be2598c2963");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9c66c658-82ce-4ae5-90ec-bf2630d207b0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9c66c658-82ce-4ae5-90ec-bf2630d207b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titlebar item.
            /// </summary>
            [RepositoryItem("35bf72d1-45be-4453-9819-3d2d323b1b63")]
            public virtual Ranorex.TitleBar Titlebar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Titlebar item info.
            /// </summary>
            [RepositoryItemInfo("35bf72d1-45be-4453-9819-3d2d323b1b63")]
            public virtual RepoItemInfo TitlebarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The TitleText item.
            /// </summary>
            [RepositoryItem("7981f32a-02cb-4ba9-9c4a-0177f8be1a32")]
            public virtual Ranorex.Text TitleText
            {
                get
                {
                    return _titletextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TitleText item info.
            /// </summary>
            [RepositoryItemInfo("7981f32a-02cb-4ba9-9c4a-0177f8be1a32")]
            public virtual RepoItemInfo TitleTextInfo
            {
                get
                {
                    return _titletextInfo;
                }
            }

            /// <summary>
            /// The MainText item.
            /// </summary>
            [RepositoryItem("b84dd048-102c-4a61-8186-92104482d0e5")]
            public virtual Ranorex.Text MainText
            {
                get
                {
                    return _maintextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MainText item info.
            /// </summary>
            [RepositoryItemInfo("b84dd048-102c-4a61-8186-92104482d0e5")]
            public virtual RepoItemInfo MainTextInfo
            {
                get
                {
                    return _maintextInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("a2075e6e-eeac-4628-9811-a556dc9c6496")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("a2075e6e-eeac-4628-9811-a556dc9c6496")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item.
            /// </summary>
            [RepositoryItem("0eb1a8d3-4498-449a-abb3-dce214c16a4e")]
            public virtual Ranorex.CheckBox IAcceptTheTermsInTheLicenseAgreem
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo.CreateAdapter<Ranorex.CheckBox>(true);
                }
            }

            /// <summary>
            /// The IAcceptTheTermsInTheLicenseAgreem item info.
            /// </summary>
            [RepositoryItemInfo("0eb1a8d3-4498-449a-abb3-dce214c16a4e")]
            public virtual RepoItemInfo IAcceptTheTermsInTheLicenseAgreemInfo
            {
                get
                {
                    return _iacceptthetermsinthelicenseagreemInfo;
                }
            }

            /// <summary>
            /// The StandaloneInstallType item.
            /// </summary>
            [RepositoryItem("449b2c02-4d5e-4d8a-90d2-b225684194de")]
            public virtual Ranorex.RadioButton StandaloneInstallType
            {
                get
                {
                    return _standaloneinstalltypeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The StandaloneInstallType item info.
            /// </summary>
            [RepositoryItemInfo("449b2c02-4d5e-4d8a-90d2-b225684194de")]
            public virtual RepoItemInfo StandaloneInstallTypeInfo
            {
                get
                {
                    return _standaloneinstalltypeInfo;
                }
            }

            /// <summary>
            /// The MultiUserInstallType item.
            /// </summary>
            [RepositoryItem("00c47a49-1db2-4aad-9b8a-3eab2bf98638")]
            public virtual Ranorex.RadioButton MultiUserInstallType
            {
                get
                {
                    return _multiuserinstalltypeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The MultiUserInstallType item info.
            /// </summary>
            [RepositoryItemInfo("00c47a49-1db2-4aad-9b8a-3eab2bf98638")]
            public virtual RepoItemInfo MultiUserInstallTypeInfo
            {
                get
                {
                    return _multiuserinstalltypeInfo;
                }
            }

            /// <summary>
            /// The TrainingInstallType item.
            /// </summary>
            [RepositoryItem("dbad87df-3fd8-4bc1-9541-b7c60e72fa06")]
            public virtual Ranorex.RadioButton TrainingInstallType
            {
                get
                {
                    return _traininginstalltypeInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The TrainingInstallType item info.
            /// </summary>
            [RepositoryItemInfo("dbad87df-3fd8-4bc1-9541-b7c60e72fa06")]
            public virtual RepoItemInfo TrainingInstallTypeInfo
            {
                get
                {
                    return _traininginstalltypeInfo;
                }
            }

            /// <summary>
            /// The UpdateTo item.
            /// </summary>
            [RepositoryItem("e6a51ee8-67a2-4082-be9b-b514ec14d9fd")]
            public virtual Ranorex.RadioButton UpdateTo
            {
                get
                {
                    return _updatetoInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The UpdateTo item info.
            /// </summary>
            [RepositoryItemInfo("e6a51ee8-67a2-4082-be9b-b514ec14d9fd")]
            public virtual RepoItemInfo UpdateToInfo
            {
                get
                {
                    return _updatetoInfo;
                }
            }

            /// <summary>
            /// The ConfirmFilepathTextbox item.
            /// </summary>
            [RepositoryItem("ec43ca31-f9f3-442d-8db1-fb90bd3baee3")]
            public virtual Ranorex.Text ConfirmFilepathTextbox
            {
                get
                {
                    return _confirmfilepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The ConfirmFilepathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("ec43ca31-f9f3-442d-8db1-fb90bd3baee3")]
            public virtual RepoItemInfo ConfirmFilepathTextboxInfo
            {
                get
                {
                    return _confirmfilepathtextboxInfo;
                }
            }

            /// <summary>
            /// The UpdateButton item.
            /// </summary>
            [RepositoryItem("9c99b1a2-54ec-4e70-8da6-e901a590d643")]
            public virtual Ranorex.Button UpdateButton
            {
                get
                {
                    return _updatebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UpdateButton item info.
            /// </summary>
            [RepositoryItemInfo("9c99b1a2-54ec-4e70-8da6-e901a590d643")]
            public virtual RepoItemInfo UpdateButtonInfo
            {
                get
                {
                    return _updatebuttonInfo;
                }
            }

            /// <summary>
            /// The FinishButton item.
            /// </summary>
            [RepositoryItem("a7259cce-3e74-4465-8f9d-93f01197f353")]
            public virtual Ranorex.Button FinishButton
            {
                get
                {
                    return _finishbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FinishButton item info.
            /// </summary>
            [RepositoryItemInfo("a7259cce-3e74-4465-8f9d-93f01197f353")]
            public virtual RepoItemInfo FinishButtonInfo
            {
                get
                {
                    return _finishbuttonInfo;
                }
            }

            /// <summary>
            /// The FilepathTextbox item.
            /// </summary>
            [RepositoryItem("bde8679d-1119-4c02-a1b5-1be2598c2963")]
            public virtual Ranorex.Text FilepathTextbox
            {
                get
                {
                    return _filepathtextboxInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FilepathTextbox item info.
            /// </summary>
            [RepositoryItemInfo("bde8679d-1119-4c02-a1b5-1be2598c2963")]
            public virtual RepoItemInfo FilepathTextboxInfo
            {
                get
                {
                    return _filepathtextboxInfo;
                }
            }

            /// <summary>
            /// The Buttons folder.
            /// </summary>
            [RepositoryFolder("21d0d719-2109-45b3-8f57-f23d927dc5b9")]
            public virtual HBAuto_Install2RepositoryFolders.ButtonsFolder Buttons
            {
                get { return _buttons; }
            }

            /// <summary>
            /// The TextContainersForValidation folder.
            /// </summary>
            [RepositoryFolder("2d05e46e-24c0-40df-b180-45954e901db1")]
            public virtual HBAuto_Install2RepositoryFolders.TextContainersForValidationFolder TextContainersForValidation
            {
                get { return _textcontainersforvalidation; }
            }
        }

        /// <summary>
        /// The ButtonsFolder folder.
        /// </summary>
        [RepositoryFolder("21d0d719-2109-45b3-8f57-f23d927dc5b9")]
        public partial class ButtonsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextbuttonInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new Buttons  folder.
            /// </summary>
            public ButtonsFolder(RepoGenBaseFolder parentFolder) :
                    base("Buttons", "", parentFolder, 0, null, false, "21d0d719-2109-45b3-8f57-f23d927dc5b9", "")
            {
                _nextbuttonInfo = new RepoItemInfo(this, "NextButton", "button[@text~'Next']", 30000, null, "9fe2014f-e363-456a-bf7c-35c0c84bac7c");
                _okbuttonInfo = new RepoItemInfo(this, "OkButton", "button[@text~'OK']", 30000, null, "c5c720fd-3d5a-4efc-b06e-909f6947d431");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("21d0d719-2109-45b3-8f57-f23d927dc5b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The NextButton item.
            /// </summary>
            [RepositoryItem("9fe2014f-e363-456a-bf7c-35c0c84bac7c")]
            public virtual Ranorex.Button NextButton
            {
                get
                {
                    return _nextbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The NextButton item info.
            /// </summary>
            [RepositoryItemInfo("9fe2014f-e363-456a-bf7c-35c0c84bac7c")]
            public virtual RepoItemInfo NextButtonInfo
            {
                get
                {
                    return _nextbuttonInfo;
                }
            }

            /// <summary>
            /// The OkButton item.
            /// </summary>
            [RepositoryItem("c5c720fd-3d5a-4efc-b06e-909f6947d431")]
            public virtual Ranorex.Button OkButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OkButton item info.
            /// </summary>
            [RepositoryItemInfo("c5c720fd-3d5a-4efc-b06e-909f6947d431")]
            public virtual RepoItemInfo OkButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The TextContainersForValidationFolder folder.
        /// </summary>
        [RepositoryFolder("2d05e46e-24c0-40df-b180-45954e901db1")]
        public partial class TextContainersForValidationFolder : RepoGenBaseFolder
        {
            HBAuto_Install2RepositoryFolders.WelcomeScreenFolder _welcomescreen;
            RepoItemInfo _titlebarInfo;

            /// <summary>
            /// Creates a new TextContainersForValidation  folder.
            /// </summary>
            public TextContainersForValidationFolder(RepoGenBaseFolder parentFolder) :
                    base("TextContainersForValidation", "", parentFolder, 0, null, false, "2d05e46e-24c0-40df-b180-45954e901db1", "")
            {
                _welcomescreen = new HBAuto_Install2RepositoryFolders.WelcomeScreenFolder(this);
                _titlebarInfo = new RepoItemInfo(this, "Titlebar", "titlebar", 30000, null, "d7991a93-eac3-47c9-bc8d-af83b1646dbe");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("2d05e46e-24c0-40df-b180-45954e901db1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Titlebar item.
            /// </summary>
            [RepositoryItem("d7991a93-eac3-47c9-bc8d-af83b1646dbe")]
            public virtual Ranorex.TitleBar Titlebar
            {
                get
                {
                    return _titlebarInfo.CreateAdapter<Ranorex.TitleBar>(true);
                }
            }

            /// <summary>
            /// The Titlebar item info.
            /// </summary>
            [RepositoryItemInfo("d7991a93-eac3-47c9-bc8d-af83b1646dbe")]
            public virtual RepoItemInfo TitlebarInfo
            {
                get
                {
                    return _titlebarInfo;
                }
            }

            /// <summary>
            /// The WelcomeScreen folder.
            /// </summary>
            [RepositoryFolder("a628127c-e21c-4155-a99f-76dc80416636")]
            public virtual HBAuto_Install2RepositoryFolders.WelcomeScreenFolder WelcomeScreen
            {
                get { return _welcomescreen; }
            }
        }

        /// <summary>
        /// The WelcomeScreenFolder folder.
        /// </summary>
        [RepositoryFolder("a628127c-e21c-4155-a99f-76dc80416636")]
        public partial class WelcomeScreenFolder : RepoGenBaseFolder
        {
            RepoItemInfo _titletextInfo;
            RepoItemInfo _maintextInfo;

            /// <summary>
            /// Creates a new WelcomeScreen  folder.
            /// </summary>
            public WelcomeScreenFolder(RepoGenBaseFolder parentFolder) :
                    base("WelcomeScreen", "", parentFolder, 0, null, false, "a628127c-e21c-4155-a99f-76dc80416636", "")
            {
                _titletextInfo = new RepoItemInfo(this, "TitleText", "text[@accessiblerole~'StaticText'][2]", 30000, null, "c0dd66b9-7a87-4b02-9101-38f62316244f");
                _maintextInfo = new RepoItemInfo(this, "MainText", "text[@accessiblerole~'StaticText'][1]", 30000, null, "d8d670a5-12f8-487a-9154-2f237ca38073");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a628127c-e21c-4155-a99f-76dc80416636")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The TitleText item.
            /// </summary>
            [RepositoryItem("c0dd66b9-7a87-4b02-9101-38f62316244f")]
            public virtual Ranorex.Text TitleText
            {
                get
                {
                    return _titletextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The TitleText item info.
            /// </summary>
            [RepositoryItemInfo("c0dd66b9-7a87-4b02-9101-38f62316244f")]
            public virtual RepoItemInfo TitleTextInfo
            {
                get
                {
                    return _titletextInfo;
                }
            }

            /// <summary>
            /// The MainText item.
            /// </summary>
            [RepositoryItem("d8d670a5-12f8-487a-9154-2f237ca38073")]
            public virtual Ranorex.Text MainText
            {
                get
                {
                    return _maintextInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The MainText item info.
            /// </summary>
            [RepositoryItemInfo("d8d670a5-12f8-487a-9154-2f237ca38073")]
            public virtual RepoItemInfo MainTextInfo
            {
                get
                {
                    return _maintextInfo;
                }
            }
        }

        /// <summary>
        /// The ConvertMultipleEstimatesAppFolder folder.
        /// </summary>
        [RepositoryFolder("91d0eedc-616b-4906-ab8f-663e09e1d2b0")]
        public partial class ConvertMultipleEstimatesAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _convertbuttonInfo;
            RepoItemInfo _cancelbuttonInfo;

            /// <summary>
            /// Creates a new ConvertMultipleEstimates  folder.
            /// </summary>
            public ConvertMultipleEstimatesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ConvertMultipleEstimates", "/form[@title~'Convert' and @title~'Multiple' and @title~'Estimate']", parentFolder, 30000, null, true, "91d0eedc-616b-4906-ab8f-663e09e1d2b0", "")
            {
                _convertbuttonInfo = new RepoItemInfo(this, "ConvertButton", ".//button[@text='Convert']", 30000, null, "09595a73-8e4c-4b44-9041-cabe260f660c");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", ".//button[@text='Cancel']", 30000, null, "84141456-f524-42a7-9fa0-65c0775b3b8b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("91d0eedc-616b-4906-ab8f-663e09e1d2b0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("91d0eedc-616b-4906-ab8f-663e09e1d2b0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ConvertButton item.
            /// </summary>
            [RepositoryItem("09595a73-8e4c-4b44-9041-cabe260f660c")]
            public virtual Ranorex.Button ConvertButton
            {
                get
                {
                    return _convertbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ConvertButton item info.
            /// </summary>
            [RepositoryItemInfo("09595a73-8e4c-4b44-9041-cabe260f660c")]
            public virtual RepoItemInfo ConvertButtonInfo
            {
                get
                {
                    return _convertbuttonInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("84141456-f524-42a7-9fa0-65c0775b3b8b")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("84141456-f524-42a7-9fa0-65c0775b3b8b")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidPopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("7b35272b-0f7e-4744-9841-fb5b2c0b875d")]
        public partial class HeavyBidPopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new HeavyBidPopup  folder.
            /// </summary>
            public HeavyBidPopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidPopup", "/form[@title='Heavybid']", parentFolder, 30000, null, true, "7b35272b-0f7e-4744-9841-fb5b2c0b875d", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "button[@text='OK']", 30000, null, "600bc51d-dfa7-4c2d-aa6c-1af6b5838c19");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7b35272b-0f7e-4744-9841-fb5b2c0b875d")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7b35272b-0f7e-4744-9841-fb5b2c0b875d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("600bc51d-dfa7-4c2d-aa6c-1af6b5838c19")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("600bc51d-dfa7-4c2d-aa6c-1af6b5838c19")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ExcelRelatedFolder folder.
        /// </summary>
        [RepositoryFolder("588390a4-0599-4f61-8881-14ed2ef9d0fb")]
        public partial class ExcelRelatedFolder : RepoGenBaseFolder
        {
            HBAuto_Install2RepositoryFolders.ExcelAppFolder _excel;
            HBAuto_Install2RepositoryFolders.ExcelXMLPopupAppFolder _excelxmlpopup;
            HBAuto_Install2RepositoryFolders.OpenXMLAppFolder _openxml;

            /// <summary>
            /// Creates a new ExcelRelated  folder.
            /// </summary>
            public ExcelRelatedFolder(RepoGenBaseFolder parentFolder) :
                    base("ExcelRelated", "", parentFolder, 0, null, false, "588390a4-0599-4f61-8881-14ed2ef9d0fb", "")
            {
                _excel = new HBAuto_Install2RepositoryFolders.ExcelAppFolder(this);
                _excelxmlpopup = new HBAuto_Install2RepositoryFolders.ExcelXMLPopupAppFolder(this);
                _openxml = new HBAuto_Install2RepositoryFolders.OpenXMLAppFolder(this);
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("588390a4-0599-4f61-8881-14ed2ef9d0fb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Excel folder.
            /// </summary>
            [RepositoryFolder("aa474a8a-f67a-40a0-a744-9d6188454193")]
            public virtual HBAuto_Install2RepositoryFolders.ExcelAppFolder Excel
            {
                get { return _excel; }
            }

            /// <summary>
            /// The ExcelXMLPopup folder.
            /// </summary>
            [RepositoryFolder("f48a685f-8cc7-4ef4-b8cf-2f3f2fc9a741")]
            public virtual HBAuto_Install2RepositoryFolders.ExcelXMLPopupAppFolder ExcelXMLPopup
            {
                get { return _excelxmlpopup; }
            }

            /// <summary>
            /// The OpenXML folder.
            /// </summary>
            [RepositoryFolder("f34ef747-2ac3-4288-93a4-92863164c2c2")]
            public virtual HBAuto_Install2RepositoryFolders.OpenXMLAppFolder OpenXML
            {
                get { return _openxml; }
            }
        }

        /// <summary>
        /// The ExcelAppFolder folder.
        /// </summary>
        [RepositoryFolder("aa474a8a-f67a-40a0-a744-9d6188454193")]
        public partial class ExcelAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cella1Info;
            RepoItemInfo _cellc10Info;
            RepoItemInfo _cellc12Info;
            RepoItemInfo _cella2Info;
            RepoItemInfo _cellb2Info;

            /// <summary>
            /// Creates a new Excel  folder.
            /// </summary>
            public ExcelAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Excel", "/form[@processname='EXCEL']", parentFolder, 30000, null, false, "aa474a8a-f67a-40a0-a744-9d6188454193", "")
            {
                _cella1Info = new RepoItemInfo(this, "CellA1", ".//table/row[@index='1']/cell[@address='A1']", 30000, null, "b52d5b97-1968-4b6a-9e93-0997d8ee55d4");
                _cellc10Info = new RepoItemInfo(this, "CellC10", ".//table/row[@index='10']/cell[@address='C10']", 30000, null, "2231ddf1-0113-4f7f-9319-cfad9d6885b2");
                _cellc12Info = new RepoItemInfo(this, "CellC12", ".//table/row[@index='12']/cell[@address='C12']", 30000, null, "c9b2f593-ec0c-4a68-8ae5-7fa22ea995e3");
                _cella2Info = new RepoItemInfo(this, "CellA2", ".//table/row[@index='2']/cell[@address='A2']", 30000, null, "7cbacd22-8b54-4eb4-a5da-459b809b2f92");
                _cellb2Info = new RepoItemInfo(this, "CellB2", ".//table/row[@index='2']/cell[@address='B2']", 30000, null, "9c4c1e1d-9152-4c45-88ae-046cc0c00de4");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("aa474a8a-f67a-40a0-a744-9d6188454193")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("aa474a8a-f67a-40a0-a744-9d6188454193")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The CellA1 item.
            /// </summary>
            [RepositoryItem("b52d5b97-1968-4b6a-9e93-0997d8ee55d4")]
            public virtual Ranorex.Cell CellA1
            {
                get
                {
                    return _cella1Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellA1 item info.
            /// </summary>
            [RepositoryItemInfo("b52d5b97-1968-4b6a-9e93-0997d8ee55d4")]
            public virtual RepoItemInfo CellA1Info
            {
                get
                {
                    return _cella1Info;
                }
            }

            /// <summary>
            /// The CellC10 item.
            /// </summary>
            [RepositoryItem("2231ddf1-0113-4f7f-9319-cfad9d6885b2")]
            public virtual Ranorex.Cell CellC10
            {
                get
                {
                    return _cellc10Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellC10 item info.
            /// </summary>
            [RepositoryItemInfo("2231ddf1-0113-4f7f-9319-cfad9d6885b2")]
            public virtual RepoItemInfo CellC10Info
            {
                get
                {
                    return _cellc10Info;
                }
            }

            /// <summary>
            /// The CellC12 item.
            /// </summary>
            [RepositoryItem("c9b2f593-ec0c-4a68-8ae5-7fa22ea995e3")]
            public virtual Ranorex.Cell CellC12
            {
                get
                {
                    return _cellc12Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellC12 item info.
            /// </summary>
            [RepositoryItemInfo("c9b2f593-ec0c-4a68-8ae5-7fa22ea995e3")]
            public virtual RepoItemInfo CellC12Info
            {
                get
                {
                    return _cellc12Info;
                }
            }

            /// <summary>
            /// The CellA2 item.
            /// </summary>
            [RepositoryItem("7cbacd22-8b54-4eb4-a5da-459b809b2f92")]
            public virtual Ranorex.Cell CellA2
            {
                get
                {
                    return _cella2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellA2 item info.
            /// </summary>
            [RepositoryItemInfo("7cbacd22-8b54-4eb4-a5da-459b809b2f92")]
            public virtual RepoItemInfo CellA2Info
            {
                get
                {
                    return _cella2Info;
                }
            }

            /// <summary>
            /// The CellB2 item.
            /// </summary>
            [RepositoryItem("9c4c1e1d-9152-4c45-88ae-046cc0c00de4")]
            public virtual Ranorex.Cell CellB2
            {
                get
                {
                    return _cellb2Info.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The CellB2 item info.
            /// </summary>
            [RepositoryItemInfo("9c4c1e1d-9152-4c45-88ae-046cc0c00de4")]
            public virtual RepoItemInfo CellB2Info
            {
                get
                {
                    return _cellb2Info;
                }
            }
        }

        /// <summary>
        /// The ExcelXMLPopupAppFolder folder.
        /// </summary>
        [RepositoryFolder("f48a685f-8cc7-4ef4-b8cf-2f3f2fc9a741")]
        public partial class ExcelXMLPopupAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _okbuttonInfo;
            RepoItemInfo _dontsavebuttonInfo;

            /// <summary>
            /// Creates a new ExcelXMLPopup  folder.
            /// </summary>
            public ExcelXMLPopupAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExcelXMLPopup", "/form[@title='Microsoft Excel']", parentFolder, 30000, null, false, "f48a685f-8cc7-4ef4-b8cf-2f3f2fc9a741", "")
            {
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "button[@text='OK']", 30000, null, "a55dfa27-558b-4460-b646-b85648c70232");
                _dontsavebuttonInfo = new RepoItemInfo(this, "DontSaveButton", ".//button[@name='Don''t Save']", 30000, null, "38ca34f7-fc65-416c-9295-d0dc227fad4b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f48a685f-8cc7-4ef4-b8cf-2f3f2fc9a741")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f48a685f-8cc7-4ef4-b8cf-2f3f2fc9a741")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("a55dfa27-558b-4460-b646-b85648c70232")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("a55dfa27-558b-4460-b646-b85648c70232")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }

            /// <summary>
            /// The DontSaveButton item.
            /// </summary>
            [RepositoryItem("38ca34f7-fc65-416c-9295-d0dc227fad4b")]
            public virtual Ranorex.Button DontSaveButton
            {
                get
                {
                    return _dontsavebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The DontSaveButton item info.
            /// </summary>
            [RepositoryItemInfo("38ca34f7-fc65-416c-9295-d0dc227fad4b")]
            public virtual RepoItemInfo DontSaveButtonInfo
            {
                get
                {
                    return _dontsavebuttonInfo;
                }
            }
        }

        /// <summary>
        /// The OpenXMLAppFolder folder.
        /// </summary>
        [RepositoryFolder("f34ef747-2ac3-4288-93a4-92863164c2c2")]
        public partial class OpenXMLAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _xmltableInfo;
            RepoItemInfo _okbuttonInfo;

            /// <summary>
            /// Creates a new OpenXML  folder.
            /// </summary>
            public OpenXMLAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OpenXML", "/form[@title='Open XML']", parentFolder, 30000, null, false, "f34ef747-2ac3-4288-93a4-92863164c2c2", "")
            {
                _xmltableInfo = new RepoItemInfo(this, "xmlTable", "radiobutton[@accessiblename='As an XML table']", 30000, null, "ed3fd7f5-7a5b-412a-beb4-91dd89adb1a0");
                _okbuttonInfo = new RepoItemInfo(this, "OKButton", "button[@text='OK']", 30000, null, "dc49d84c-6e05-40b9-ab75-b72431db3a16");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("f34ef747-2ac3-4288-93a4-92863164c2c2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("f34ef747-2ac3-4288-93a4-92863164c2c2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The xmlTable item.
            /// </summary>
            [RepositoryItem("ed3fd7f5-7a5b-412a-beb4-91dd89adb1a0")]
            public virtual Ranorex.RadioButton xmlTable
            {
                get
                {
                    return _xmltableInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The xmlTable item info.
            /// </summary>
            [RepositoryItemInfo("ed3fd7f5-7a5b-412a-beb4-91dd89adb1a0")]
            public virtual RepoItemInfo xmlTableInfo
            {
                get
                {
                    return _xmltableInfo;
                }
            }

            /// <summary>
            /// The OKButton item.
            /// </summary>
            [RepositoryItem("dc49d84c-6e05-40b9-ab75-b72431db3a16")]
            public virtual Ranorex.Button OKButton
            {
                get
                {
                    return _okbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The OKButton item info.
            /// </summary>
            [RepositoryItemInfo("dc49d84c-6e05-40b9-ab75-b72431db3a16")]
            public virtual RepoItemInfo OKButtonInfo
            {
                get
                {
                    return _okbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The ProgramsAndFeaturesAppFolder folder.
        /// </summary>
        [RepositoryFolder("900ba1a3-8153-4751-8e0d-8cca1362b5c3")]
        public partial class ProgramsAndFeaturesAppFolder : RepoGenBaseFolder
        {
            HBAuto_Install2RepositoryFolders.ButtonsFolder1 _buttons;
            HBAuto_Install2RepositoryFolders.UninstallProgramTableFolder _uninstallprogramtable;
            RepoItemInfo _searcheditboxInfo;
            RepoItemInfo _uninstallbuttonInfo;
            RepoItemInfo _yesbuttonInfo;
            RepoItemInfo _buttinuninstallorchangeInfo;

            /// <summary>
            /// Creates a new ProgramsAndFeatures  folder.
            /// </summary>
            public ProgramsAndFeaturesAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ProgramsAndFeatures", "/form[@title~'Programs and Features']", parentFolder, 30000, null, false, "900ba1a3-8153-4751-8e0d-8cca1362b5c3", "")
            {
                _buttons = new HBAuto_Install2RepositoryFolders.ButtonsFolder1(this);
                _uninstallprogramtable = new HBAuto_Install2RepositoryFolders.UninstallProgramTableFolder(this);
                _searcheditboxInfo = new RepoItemInfo(this, "SearchEditBox", "?/?/?/?/element[@class='Search Box']", 30000, null, "0b381acf-a7c7-46ee-a3ef-c13bbf56b765");
                _uninstallbuttonInfo = new RepoItemInfo(this, "UninstallButton", ".//container[@automationid='FolderLayoutContainer']/container[@classname='Element']/toolbar/button[@text~'Uninstall']", 30000, null, "c515c285-d252-47d9-9f0b-4931f55026d7");
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", "?/?/element/button[@text='&Yes']", 30000, null, "fc6c435a-bb04-427a-8762-f74839f6c842");
                _buttinuninstallorchangeInfo = new RepoItemInfo(this, "ButtinUninstallOrChange", ".//container[@automationid='FolderLayoutContainer']/container[@classname='Element']/toolbar/button[@text~'Uninstall']", 30000, null, "ed24880f-0778-420d-ac9f-7ba7c27a81f9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("900ba1a3-8153-4751-8e0d-8cca1362b5c3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("900ba1a3-8153-4751-8e0d-8cca1362b5c3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SearchEditBox item.
            /// </summary>
            [RepositoryItem("0b381acf-a7c7-46ee-a3ef-c13bbf56b765")]
            public virtual Ranorex.Unknown SearchEditBox
            {
                get
                {
                    return _searcheditboxInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SearchEditBox item info.
            /// </summary>
            [RepositoryItemInfo("0b381acf-a7c7-46ee-a3ef-c13bbf56b765")]
            public virtual RepoItemInfo SearchEditBoxInfo
            {
                get
                {
                    return _searcheditboxInfo;
                }
            }

            /// <summary>
            /// The UninstallButton item.
            /// </summary>
            [RepositoryItem("c515c285-d252-47d9-9f0b-4931f55026d7")]
            public virtual Ranorex.Button UninstallButton
            {
                get
                {
                    return _uninstallbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UninstallButton item info.
            /// </summary>
            [RepositoryItemInfo("c515c285-d252-47d9-9f0b-4931f55026d7")]
            public virtual RepoItemInfo UninstallButtonInfo
            {
                get
                {
                    return _uninstallbuttonInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("fc6c435a-bb04-427a-8762-f74839f6c842")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("fc6c435a-bb04-427a-8762-f74839f6c842")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }

            /// <summary>
            /// The ButtinUninstallOrChange item.
            /// </summary>
            [RepositoryItem("ed24880f-0778-420d-ac9f-7ba7c27a81f9")]
            public virtual Ranorex.Button ButtinUninstallOrChange
            {
                get
                {
                    return _buttinuninstallorchangeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtinUninstallOrChange item info.
            /// </summary>
            [RepositoryItemInfo("ed24880f-0778-420d-ac9f-7ba7c27a81f9")]
            public virtual RepoItemInfo ButtinUninstallOrChangeInfo
            {
                get
                {
                    return _buttinuninstallorchangeInfo;
                }
            }

            /// <summary>
            /// The Buttons folder.
            /// </summary>
            [RepositoryFolder("e000c4a8-6913-4f64-91b6-bad59ca5b9b9")]
            public virtual HBAuto_Install2RepositoryFolders.ButtonsFolder1 Buttons
            {
                get { return _buttons; }
            }

            /// <summary>
            /// The UninstallProgramTable folder.
            /// </summary>
            [RepositoryFolder("8148e041-2347-4ff4-a99a-ae2b9d211b29")]
            public virtual HBAuto_Install2RepositoryFolders.UninstallProgramTableFolder UninstallProgramTable
            {
                get { return _uninstallprogramtable; }
            }
        }

        /// <summary>
        /// The ButtonsFolder1 folder.
        /// </summary>
        [RepositoryFolder("e000c4a8-6913-4f64-91b6-bad59ca5b9b9")]
        public partial class ButtonsFolder1 : RepoGenBaseFolder
        {
            RepoItemInfo _uninstallbuttonInfo;
            RepoItemInfo _yesbuttonInfo;

            /// <summary>
            /// Creates a new Buttons  folder.
            /// </summary>
            public ButtonsFolder1(RepoGenBaseFolder parentFolder) :
                    base("Buttons", "", parentFolder, 0, null, false, "e000c4a8-6913-4f64-91b6-bad59ca5b9b9", "")
            {
                _uninstallbuttonInfo = new RepoItemInfo(this, "UninstallButton", ".//container[@automationid='FolderLayoutContainer']/container[@classname='Element']/toolbar/button[@text~'Uninstall']", 30000, null, "8526e365-08b1-42f7-a7d9-fcae686aa8db");
                _yesbuttonInfo = new RepoItemInfo(this, "YesButton", "?/?/element/button[@text='&Yes']", 30000, null, "06b2be20-04ca-41c3-8491-bfb80bd884a9");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e000c4a8-6913-4f64-91b6-bad59ca5b9b9")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UninstallButton item.
            /// </summary>
            [RepositoryItem("8526e365-08b1-42f7-a7d9-fcae686aa8db")]
            public virtual Ranorex.Button UninstallButton
            {
                get
                {
                    return _uninstallbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The UninstallButton item info.
            /// </summary>
            [RepositoryItemInfo("8526e365-08b1-42f7-a7d9-fcae686aa8db")]
            public virtual RepoItemInfo UninstallButtonInfo
            {
                get
                {
                    return _uninstallbuttonInfo;
                }
            }

            /// <summary>
            /// The YesButton item.
            /// </summary>
            [RepositoryItem("06b2be20-04ca-41c3-8491-bfb80bd884a9")]
            public virtual Ranorex.Button YesButton
            {
                get
                {
                    return _yesbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The YesButton item info.
            /// </summary>
            [RepositoryItemInfo("06b2be20-04ca-41c3-8491-bfb80bd884a9")]
            public virtual RepoItemInfo YesButtonInfo
            {
                get
                {
                    return _yesbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The UninstallProgramTableFolder folder.
        /// </summary>
        [RepositoryFolder("8148e041-2347-4ff4-a99a-ae2b9d211b29")]
        public partial class UninstallProgramTableFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hcsscrystalxiintegrationInfo;
            RepoItemInfo _microsoftsqlserver2012nativeclientInfo;
            RepoItemInfo _heavybidworkstationInfo;

            /// <summary>
            /// Creates a new UninstallProgramTable  folder.
            /// </summary>
            public UninstallProgramTableFolder(RepoGenBaseFolder parentFolder) :
                    base("UninstallProgramTable", ".//container[@caption='ShellView']/table/row[@index>='0']", parentFolder, 30000, null, false, "8148e041-2347-4ff4-a99a-ae2b9d211b29", "")
            {
                _hcsscrystalxiintegrationInfo = new RepoItemInfo(this, "HCSSCrystalXIIntegration", "cell[@text~'^HCSS\\ -\\ Crystal\\ XI\\ Integra']", 30000, null, "1900bacc-3b6a-44f6-aafc-486cfa9d8b1b");
                _microsoftsqlserver2012nativeclientInfo = new RepoItemInfo(this, "MicrosoftSQLServer2012NativeClient", "cell[@text~'^Microsoft\\ SQL\\ Server\\ 2012']", 30000, null, "9ea0b998-002d-4d44-821b-b6afc5b721a8");
                _heavybidworkstationInfo = new RepoItemInfo(this, "HeavyBidWorkstation", "cell[@text='HeavyBid Workstation']", 30000, null, "1d5967c9-68da-4c64-8967-a67e3d68a2bf");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8148e041-2347-4ff4-a99a-ae2b9d211b29")]
            public virtual Ranorex.Row Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Row>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8148e041-2347-4ff4-a99a-ae2b9d211b29")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HCSSCrystalXIIntegration item.
            /// </summary>
            [RepositoryItem("1900bacc-3b6a-44f6-aafc-486cfa9d8b1b")]
            public virtual Ranorex.Cell HCSSCrystalXIIntegration
            {
                get
                {
                    return _hcsscrystalxiintegrationInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The HCSSCrystalXIIntegration item info.
            /// </summary>
            [RepositoryItemInfo("1900bacc-3b6a-44f6-aafc-486cfa9d8b1b")]
            public virtual RepoItemInfo HCSSCrystalXIIntegrationInfo
            {
                get
                {
                    return _hcsscrystalxiintegrationInfo;
                }
            }

            /// <summary>
            /// The MicrosoftSQLServer2012NativeClient item.
            /// </summary>
            [RepositoryItem("9ea0b998-002d-4d44-821b-b6afc5b721a8")]
            public virtual Ranorex.Cell MicrosoftSQLServer2012NativeClient
            {
                get
                {
                    return _microsoftsqlserver2012nativeclientInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The MicrosoftSQLServer2012NativeClient item info.
            /// </summary>
            [RepositoryItemInfo("9ea0b998-002d-4d44-821b-b6afc5b721a8")]
            public virtual RepoItemInfo MicrosoftSQLServer2012NativeClientInfo
            {
                get
                {
                    return _microsoftsqlserver2012nativeclientInfo;
                }
            }

            /// <summary>
            /// The HeavyBidWorkstation item.
            /// </summary>
            [RepositoryItem("1d5967c9-68da-4c64-8967-a67e3d68a2bf")]
            public virtual Ranorex.Cell HeavyBidWorkstation
            {
                get
                {
                    return _heavybidworkstationInfo.CreateAdapter<Ranorex.Cell>(true);
                }
            }

            /// <summary>
            /// The HeavyBidWorkstation item info.
            /// </summary>
            [RepositoryItemInfo("1d5967c9-68da-4c64-8967-a67e3d68a2bf")]
            public virtual RepoItemInfo HeavyBidWorkstationInfo
            {
                get
                {
                    return _heavybidworkstationInfo;
                }
            }
        }

        /// <summary>
        /// The HeavyBidUninstallAppFolder folder.
        /// </summary>
        [RepositoryFolder("82b00af4-ca5f-4ecf-a138-80c06109b889")]
        public partial class HeavyBidUninstallAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonyesInfo;

            /// <summary>
            /// Creates a new HeavyBidUninstall  folder.
            /// </summary>
            public HeavyBidUninstallAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HeavyBidUninstall", "/form[@title='HeavyBid Uninstall']", parentFolder, 30000, null, false, "82b00af4-ca5f-4ecf-a138-80c06109b889", "")
            {
                _buttonyesInfo = new RepoItemInfo(this, "ButtonYes", "button[@text='&Yes']", 30000, null, "a092a07a-79a3-47bb-8324-7a6c60872151");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("82b00af4-ca5f-4ecf-a138-80c06109b889")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("82b00af4-ca5f-4ecf-a138-80c06109b889")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonYes item.
            /// </summary>
            [RepositoryItem("a092a07a-79a3-47bb-8324-7a6c60872151")]
            public virtual Ranorex.Button ButtonYes
            {
                get
                {
                    return _buttonyesInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonYes item info.
            /// </summary>
            [RepositoryItemInfo("a092a07a-79a3-47bb-8324-7a6c60872151")]
            public virtual RepoItemInfo ButtonYesInfo
            {
                get
                {
                    return _buttonyesInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}